version: '3.8'
services:
  dabase:
    container_name: nest_postgres_db
    image: postgres:14.5-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=nest_authorization
    ports:
      - '5432:5432'
    volumes:
      - postgres_volume:/var/lib/postgresql/data
  api:
    build: .
    env_file: ./.env
    command: npm run start:dev
    depends_on:
      - dabase
    ports:
      - "5000:5000"
    volumes:
      - .:/usr/src/ap
volumes:
  postgres_volume:

