version: '3.8'

services:
  db:
    container_name: nest_postgres
    image: postgres:14.5-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=nest_authorization
    ports:
      - '5080:5432'
    volumes:
      - postgres_volume:/var/lib/postgresql/data
volumes:
  postgres_volume:

